name: CI

on:
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug
        tags:
          description: 'Test scenario tags'
          required: false
          type: boolean
        environment:
          description: 'Environment to run tests against'
          type: environment
          required: true

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install flake8
        run: pip install flake8 flake8-pyproject

      - name: Run flake8
        run: flake8 .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install mypy
        run: pip install mypy

      - name: Run mypy
        run: |
          find . -name "*.py" -not -path "./venv/*" -not -path "./.git/*" -not -path "./.github/*" > python_files.txt
          mypy --install-types --non-interactive --strict $(cat python_files.txt)